Preliminary arima model task 8
awdleishman/almanac pull request #17
Opened 2023-11-01 13:20 UTC by Chips421

Created Models.py to house functions for different models going forward. Additionally created preliminary ARIMA, SARIMA, and HW models.

2023-11-01 15:30 UTC, awdleishman requested changes

2023-11-01 15:30 UTC, awdleishman commented on Almanac/Models.py
> +        train["tmin"].resample("W").min(),
Would it make more sense to handle this resampling as a preprocessing step, rather than in the training function?

2023-11-01 15:30 UTC, awdleishman commented on Almanac/Models.py
> +    predicted = fitted_model.forecast(52)
Could we parametrize this to predict the next `n` weeks instead of hardcoding it to 52?

2023-11-01 15:30 UTC, awdleishman commented on Almanac/Models.py
> +    location: str (optional)
I feel like rather than exposing the model to out of sample data, we should instead cut the last X fraction of the training data and then use that to optimize the offset.

That way you only need to pass one dataset during training, and you can still use that out of sample dataset for a fair measure of model performance after training

2023-11-01 15:30 UTC, awdleishman commented on Almanac/Models.py
> +         to a max offset of 3.5.
Isn't the max offset shown above 7?

2023-11-01 15:30 UTC, awdleishman commented on Untitled.ipynb
- [x] rename or remove

2023-11-01 15:30 UTC, awdleishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Try ARIMA model](https://trello.com/c/uGousjCD/8-try-arima-model)

2023-11-06 15:23 UTC, Chips421 commented on Almanac/Models.py
> +        train["tmin"].resample("W").min(),
I've updated this to give us the option of whether or not to handle resampling as a preprocessing step or not. The function will now check the frequency of the train dataset and resample if it is not weekly.

2023-11-06 15:23 UTC, Chips421 commented on Almanac/Models.py
> +    predicted = fitted_model.forecast(52)
Done.

2023-11-06 15:24 UTC, Chips421 commented on Almanac/Models.py
> +    location: str (optional)
Done. Though this does require training the model twice, however, I don't think it will cause any significant performance issues.

2023-11-06 15:26 UTC, Chips421 commented on Almanac/Models.py
> +         to a max offset of 3.5.
The max offset shown was actually 6.5 since range is not inclusive of the endpoint, but I have parameterized the max offset.

2023-11-06 15:26 UTC, Chips421 commented on Untitled.ipynb
Done.

2023-11-09 16:41 UTC, awdleishman approved these changes, later dismissed
Thanks for the updates, looks good!

2023-11-09 16:41 UTC, awdleishman commented on .ipynb_checkpoints/HW TS testing workspace-checkpoint.ipynb
- [ ] remove

2023-11-09 21:09 UTC, awdleishman approved these changes

2023-11-09 21:09 UTC, merged