Pinning packages
awdleishman/almanac pull request #3
Opened 2023-10-05 20:07 UTC by awdleishman

2023-10-05 20:37 UTC, Chips421 requested changes
Can we include Seaborn  in the environment?

2023-10-06 00:07 UTC, awdleishman commented
> Can we include Seaborn in the environment?

Added. It's also easy to update the requirements.txt down the road if we discover we need additional packages

2023-10-06 14:55 UTC, Chips421 approved these changes

2023-10-06 15:01 UTC, merged

2023-10-06 16:26 UTC, awdleishman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup requirements.txt](https://trello.com/c/yb9Io2Cb/1-setup-requirementstxt)